pub mod accounts;
pub mod auth;
pub mod config;
pub mod email;
#[cfg(feature = "embed-ui")]
pub mod embedded_ui;
pub mod error;
pub mod extractors;
pub mod ipc;
pub mod rate_limit;
pub mod routes;
pub mod security_middleware;
pub mod server;
pub mod session_ws;
pub mod validation;
pub mod ws;
